apiVersion: dns.tailscale.buttah-cloud.io/v1alpha1
kind: Preferences
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1alpha1/preferences
  labels:
    testing.upbound.io/example-name: sample_preferences
  name: sample-preferences
spec:
  forProvider:
    magicDns: true
