// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ExternalIDInitParameters struct {
}

type ExternalIDObservation struct {

	// scenarios_third-party.html for more information on external IDs.
	// The External ID that Tailscale will supply when assuming your role. You must reference this in your IAM role's trust policy. See https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_third-party.html for more information on external IDs.
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// scenarios_third-party.html for more information on external IDs.
	// The AWS account from which Tailscale will assume your role. You must reference this in your IAM role's trust policy. See https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_third-party.html for more information on external IDs.
	TailscaleAwsAccountID *string `json:"tailscaleAwsAccountId,omitempty" tf:"tailscale_aws_account_id,omitempty"`
}

type ExternalIDParameters struct {
}

// ExternalIDSpec defines the desired state of ExternalID
type ExternalIDSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ExternalIDParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ExternalIDInitParameters `json:"initProvider,omitempty"`
}

// ExternalIDStatus defines the observed state of ExternalID.
type ExternalIDStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ExternalIDObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ExternalID is the Schema for the ExternalIDs API. The aws_external_id resource allows you to mint an AWS External ID that Tailscale can use to assume an AWS IAM role that you create for the purposes of allowing Tailscale to stream logs to your S3 bucket. See the logstream_configuration resource for more details.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,tailscale}
type ExternalID struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ExternalIDSpec   `json:"spec"`
	Status            ExternalIDStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ExternalIDList contains a list of ExternalIDs
type ExternalIDList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ExternalID `json:"items"`
}

// Repository type metadata.
var (
	ExternalID_Kind             = "ExternalID"
	ExternalID_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ExternalID_Kind}.String()
	ExternalID_KindAPIVersion   = ExternalID_Kind + "." + CRDGroupVersion.String()
	ExternalID_GroupVersionKind = CRDGroupVersion.WithKind(ExternalID_Kind)
)

func init() {
	SchemeBuilder.Register(&ExternalID{}, &ExternalIDList{})
}
