//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Key) DeepCopyInto(out *Key) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Key.
func (in *Key) DeepCopy() *Key {
	if in == nil {
		return nil
	}
	out := new(Key)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Key) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyInitParameters) DeepCopyInto(out *KeyInitParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Ephemeral != nil {
		in, out := &in.Ephemeral, &out.Ephemeral
		*out = new(bool)
		**out = **in
	}
	if in.Expiry != nil {
		in, out := &in.Expiry, &out.Expiry
		*out = new(float64)
		**out = **in
	}
	if in.Preauthorized != nil {
		in, out := &in.Preauthorized, &out.Preauthorized
		*out = new(bool)
		**out = **in
	}
	if in.RecreateIfInvalid != nil {
		in, out := &in.RecreateIfInvalid, &out.RecreateIfInvalid
		*out = new(string)
		**out = **in
	}
	if in.Reusable != nil {
		in, out := &in.Reusable, &out.Reusable
		*out = new(bool)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyInitParameters.
func (in *KeyInitParameters) DeepCopy() *KeyInitParameters {
	if in == nil {
		return nil
	}
	out := new(KeyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyList) DeepCopyInto(out *KeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Key, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyList.
func (in *KeyList) DeepCopy() *KeyList {
	if in == nil {
		return nil
	}
	out := new(KeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyObservation) DeepCopyInto(out *KeyObservation) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Ephemeral != nil {
		in, out := &in.Ephemeral, &out.Ephemeral
		*out = new(bool)
		**out = **in
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = new(string)
		**out = **in
	}
	if in.Expiry != nil {
		in, out := &in.Expiry, &out.Expiry
		*out = new(float64)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Invalid != nil {
		in, out := &in.Invalid, &out.Invalid
		*out = new(bool)
		**out = **in
	}
	if in.Preauthorized != nil {
		in, out := &in.Preauthorized, &out.Preauthorized
		*out = new(bool)
		**out = **in
	}
	if in.RecreateIfInvalid != nil {
		in, out := &in.RecreateIfInvalid, &out.RecreateIfInvalid
		*out = new(string)
		**out = **in
	}
	if in.Reusable != nil {
		in, out := &in.Reusable, &out.Reusable
		*out = new(bool)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyObservation.
func (in *KeyObservation) DeepCopy() *KeyObservation {
	if in == nil {
		return nil
	}
	out := new(KeyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyParameters) DeepCopyInto(out *KeyParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Ephemeral != nil {
		in, out := &in.Ephemeral, &out.Ephemeral
		*out = new(bool)
		**out = **in
	}
	if in.Expiry != nil {
		in, out := &in.Expiry, &out.Expiry
		*out = new(float64)
		**out = **in
	}
	if in.Preauthorized != nil {
		in, out := &in.Preauthorized, &out.Preauthorized
		*out = new(bool)
		**out = **in
	}
	if in.RecreateIfInvalid != nil {
		in, out := &in.RecreateIfInvalid, &out.RecreateIfInvalid
		*out = new(string)
		**out = **in
	}
	if in.Reusable != nil {
		in, out := &in.Reusable, &out.Reusable
		*out = new(bool)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyParameters.
func (in *KeyParameters) DeepCopy() *KeyParameters {
	if in == nil {
		return nil
	}
	out := new(KeyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeySpec) DeepCopyInto(out *KeySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeySpec.
func (in *KeySpec) DeepCopy() *KeySpec {
	if in == nil {
		return nil
	}
	out := new(KeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyStatus) DeepCopyInto(out *KeyStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyStatus.
func (in *KeyStatus) DeepCopy() *KeyStatus {
	if in == nil {
		return nil
	}
	out := new(KeyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Settings) DeepCopyInto(out *Settings) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Settings.
func (in *Settings) DeepCopy() *Settings {
	if in == nil {
		return nil
	}
	out := new(Settings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Settings) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingsInitParameters) DeepCopyInto(out *SettingsInitParameters) {
	*out = *in
	if in.AclsExternalLink != nil {
		in, out := &in.AclsExternalLink, &out.AclsExternalLink
		*out = new(string)
		**out = **in
	}
	if in.AclsExternallyManagedOn != nil {
		in, out := &in.AclsExternallyManagedOn, &out.AclsExternallyManagedOn
		*out = new(bool)
		**out = **in
	}
	if in.DevicesApprovalOn != nil {
		in, out := &in.DevicesApprovalOn, &out.DevicesApprovalOn
		*out = new(bool)
		**out = **in
	}
	if in.DevicesAutoUpdatesOn != nil {
		in, out := &in.DevicesAutoUpdatesOn, &out.DevicesAutoUpdatesOn
		*out = new(bool)
		**out = **in
	}
	if in.DevicesKeyDurationDays != nil {
		in, out := &in.DevicesKeyDurationDays, &out.DevicesKeyDurationDays
		*out = new(float64)
		**out = **in
	}
	if in.HTTPSEnabled != nil {
		in, out := &in.HTTPSEnabled, &out.HTTPSEnabled
		*out = new(bool)
		**out = **in
	}
	if in.NetworkFlowLoggingOn != nil {
		in, out := &in.NetworkFlowLoggingOn, &out.NetworkFlowLoggingOn
		*out = new(bool)
		**out = **in
	}
	if in.PostureIdentityCollectionOn != nil {
		in, out := &in.PostureIdentityCollectionOn, &out.PostureIdentityCollectionOn
		*out = new(bool)
		**out = **in
	}
	if in.RegionalRoutingOn != nil {
		in, out := &in.RegionalRoutingOn, &out.RegionalRoutingOn
		*out = new(bool)
		**out = **in
	}
	if in.UsersApprovalOn != nil {
		in, out := &in.UsersApprovalOn, &out.UsersApprovalOn
		*out = new(bool)
		**out = **in
	}
	if in.UsersRoleAllowedToJoinExternalTailnet != nil {
		in, out := &in.UsersRoleAllowedToJoinExternalTailnet, &out.UsersRoleAllowedToJoinExternalTailnet
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingsInitParameters.
func (in *SettingsInitParameters) DeepCopy() *SettingsInitParameters {
	if in == nil {
		return nil
	}
	out := new(SettingsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingsList) DeepCopyInto(out *SettingsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Settings, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingsList.
func (in *SettingsList) DeepCopy() *SettingsList {
	if in == nil {
		return nil
	}
	out := new(SettingsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SettingsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingsObservation) DeepCopyInto(out *SettingsObservation) {
	*out = *in
	if in.AclsExternalLink != nil {
		in, out := &in.AclsExternalLink, &out.AclsExternalLink
		*out = new(string)
		**out = **in
	}
	if in.AclsExternallyManagedOn != nil {
		in, out := &in.AclsExternallyManagedOn, &out.AclsExternallyManagedOn
		*out = new(bool)
		**out = **in
	}
	if in.DevicesApprovalOn != nil {
		in, out := &in.DevicesApprovalOn, &out.DevicesApprovalOn
		*out = new(bool)
		**out = **in
	}
	if in.DevicesAutoUpdatesOn != nil {
		in, out := &in.DevicesAutoUpdatesOn, &out.DevicesAutoUpdatesOn
		*out = new(bool)
		**out = **in
	}
	if in.DevicesKeyDurationDays != nil {
		in, out := &in.DevicesKeyDurationDays, &out.DevicesKeyDurationDays
		*out = new(float64)
		**out = **in
	}
	if in.HTTPSEnabled != nil {
		in, out := &in.HTTPSEnabled, &out.HTTPSEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.NetworkFlowLoggingOn != nil {
		in, out := &in.NetworkFlowLoggingOn, &out.NetworkFlowLoggingOn
		*out = new(bool)
		**out = **in
	}
	if in.PostureIdentityCollectionOn != nil {
		in, out := &in.PostureIdentityCollectionOn, &out.PostureIdentityCollectionOn
		*out = new(bool)
		**out = **in
	}
	if in.RegionalRoutingOn != nil {
		in, out := &in.RegionalRoutingOn, &out.RegionalRoutingOn
		*out = new(bool)
		**out = **in
	}
	if in.UsersApprovalOn != nil {
		in, out := &in.UsersApprovalOn, &out.UsersApprovalOn
		*out = new(bool)
		**out = **in
	}
	if in.UsersRoleAllowedToJoinExternalTailnet != nil {
		in, out := &in.UsersRoleAllowedToJoinExternalTailnet, &out.UsersRoleAllowedToJoinExternalTailnet
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingsObservation.
func (in *SettingsObservation) DeepCopy() *SettingsObservation {
	if in == nil {
		return nil
	}
	out := new(SettingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingsParameters) DeepCopyInto(out *SettingsParameters) {
	*out = *in
	if in.AclsExternalLink != nil {
		in, out := &in.AclsExternalLink, &out.AclsExternalLink
		*out = new(string)
		**out = **in
	}
	if in.AclsExternallyManagedOn != nil {
		in, out := &in.AclsExternallyManagedOn, &out.AclsExternallyManagedOn
		*out = new(bool)
		**out = **in
	}
	if in.DevicesApprovalOn != nil {
		in, out := &in.DevicesApprovalOn, &out.DevicesApprovalOn
		*out = new(bool)
		**out = **in
	}
	if in.DevicesAutoUpdatesOn != nil {
		in, out := &in.DevicesAutoUpdatesOn, &out.DevicesAutoUpdatesOn
		*out = new(bool)
		**out = **in
	}
	if in.DevicesKeyDurationDays != nil {
		in, out := &in.DevicesKeyDurationDays, &out.DevicesKeyDurationDays
		*out = new(float64)
		**out = **in
	}
	if in.HTTPSEnabled != nil {
		in, out := &in.HTTPSEnabled, &out.HTTPSEnabled
		*out = new(bool)
		**out = **in
	}
	if in.NetworkFlowLoggingOn != nil {
		in, out := &in.NetworkFlowLoggingOn, &out.NetworkFlowLoggingOn
		*out = new(bool)
		**out = **in
	}
	if in.PostureIdentityCollectionOn != nil {
		in, out := &in.PostureIdentityCollectionOn, &out.PostureIdentityCollectionOn
		*out = new(bool)
		**out = **in
	}
	if in.RegionalRoutingOn != nil {
		in, out := &in.RegionalRoutingOn, &out.RegionalRoutingOn
		*out = new(bool)
		**out = **in
	}
	if in.UsersApprovalOn != nil {
		in, out := &in.UsersApprovalOn, &out.UsersApprovalOn
		*out = new(bool)
		**out = **in
	}
	if in.UsersRoleAllowedToJoinExternalTailnet != nil {
		in, out := &in.UsersRoleAllowedToJoinExternalTailnet, &out.UsersRoleAllowedToJoinExternalTailnet
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingsParameters.
func (in *SettingsParameters) DeepCopy() *SettingsParameters {
	if in == nil {
		return nil
	}
	out := new(SettingsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingsSpec) DeepCopyInto(out *SettingsSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingsSpec.
func (in *SettingsSpec) DeepCopy() *SettingsSpec {
	if in == nil {
		return nil
	}
	out := new(SettingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingsStatus) DeepCopyInto(out *SettingsStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingsStatus.
func (in *SettingsStatus) DeepCopy() *SettingsStatus {
	if in == nil {
		return nil
	}
	out := new(SettingsStatus)
	in.DeepCopyInto(out)
	return out
}
