// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type SettingsInitParameters struct {

	// (String) Link to your external ACL definition or management system. Must be a valid URL.
	// Link to your external ACL definition or management system. Must be a valid URL.
	AclsExternalLink *string `json:"aclsExternalLink,omitempty" tf:"acls_external_link,omitempty"`

	AclsExternallyManagedOn *bool `json:"aclsExternallyManagedOn,omitempty" tf:"acls_externally_managed_on,omitempty"`

	// (Boolean) Whether device approval is enabled for the tailnet
	// Whether device approval is enabled for the tailnet
	DevicesApprovalOn *bool `json:"devicesApprovalOn,omitempty" tf:"devices_approval_on,omitempty"`

	// (Boolean) Whether auto updates are enabled for devices that belong to this tailnet
	// Whether auto updates are enabled for devices that belong to this tailnet
	DevicesAutoUpdatesOn *bool `json:"devicesAutoUpdatesOn,omitempty" tf:"devices_auto_updates_on,omitempty"`

	// (Number) The key expiry duration for devices on this tailnet
	// The key expiry duration for devices on this tailnet
	DevicesKeyDurationDays *float64 `json:"devicesKeyDurationDays,omitempty" tf:"devices_key_duration_days,omitempty"`

	// (Boolean) Whether provisioning of HTTPS certificates is enabled for the tailnet
	// Whether provisioning of HTTPS certificates is enabled for the tailnet
	HTTPSEnabled *bool `json:"httpsEnabled,omitempty" tf:"https_enabled,omitempty"`

	// (Boolean) Whether network flow logs are enabled for the tailnet
	// Whether network flow logs are enabled for the tailnet
	NetworkFlowLoggingOn *bool `json:"networkFlowLoggingOn,omitempty" tf:"network_flow_logging_on,omitempty"`

	// (Boolean) Whether identity collection is enabled for device posture integrations for the tailnet
	// Whether identity collection is enabled for device posture integrations for the tailnet
	PostureIdentityCollectionOn *bool `json:"postureIdentityCollectionOn,omitempty" tf:"posture_identity_collection_on,omitempty"`

	// (Boolean) Whether regional routing is enabled for the tailnet
	// Whether regional routing is enabled for the tailnet
	RegionalRoutingOn *bool `json:"regionalRoutingOn,omitempty" tf:"regional_routing_on,omitempty"`

	// (Boolean) Whether user approval is enabled for this tailnet
	// Whether user approval is enabled for this tailnet
	UsersApprovalOn *bool `json:"usersApprovalOn,omitempty" tf:"users_approval_on,omitempty"`

	// (String) Which user roles are allowed to join external tailnets
	// Which user roles are allowed to join external tailnets
	UsersRoleAllowedToJoinExternalTailnet *string `json:"usersRoleAllowedToJoinExternalTailnet,omitempty" tf:"users_role_allowed_to_join_external_tailnet,omitempty"`
}

type SettingsObservation struct {

	// (String) Link to your external ACL definition or management system. Must be a valid URL.
	// Link to your external ACL definition or management system. Must be a valid URL.
	AclsExternalLink *string `json:"aclsExternalLink,omitempty" tf:"acls_external_link,omitempty"`

	AclsExternallyManagedOn *bool `json:"aclsExternallyManagedOn,omitempty" tf:"acls_externally_managed_on,omitempty"`

	// (Boolean) Whether device approval is enabled for the tailnet
	// Whether device approval is enabled for the tailnet
	DevicesApprovalOn *bool `json:"devicesApprovalOn,omitempty" tf:"devices_approval_on,omitempty"`

	// (Boolean) Whether auto updates are enabled for devices that belong to this tailnet
	// Whether auto updates are enabled for devices that belong to this tailnet
	DevicesAutoUpdatesOn *bool `json:"devicesAutoUpdatesOn,omitempty" tf:"devices_auto_updates_on,omitempty"`

	// (Number) The key expiry duration for devices on this tailnet
	// The key expiry duration for devices on this tailnet
	DevicesKeyDurationDays *float64 `json:"devicesKeyDurationDays,omitempty" tf:"devices_key_duration_days,omitempty"`

	// (Boolean) Whether provisioning of HTTPS certificates is enabled for the tailnet
	// Whether provisioning of HTTPS certificates is enabled for the tailnet
	HTTPSEnabled *bool `json:"httpsEnabled,omitempty" tf:"https_enabled,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Whether network flow logs are enabled for the tailnet
	// Whether network flow logs are enabled for the tailnet
	NetworkFlowLoggingOn *bool `json:"networkFlowLoggingOn,omitempty" tf:"network_flow_logging_on,omitempty"`

	// (Boolean) Whether identity collection is enabled for device posture integrations for the tailnet
	// Whether identity collection is enabled for device posture integrations for the tailnet
	PostureIdentityCollectionOn *bool `json:"postureIdentityCollectionOn,omitempty" tf:"posture_identity_collection_on,omitempty"`

	// (Boolean) Whether regional routing is enabled for the tailnet
	// Whether regional routing is enabled for the tailnet
	RegionalRoutingOn *bool `json:"regionalRoutingOn,omitempty" tf:"regional_routing_on,omitempty"`

	// (Boolean) Whether user approval is enabled for this tailnet
	// Whether user approval is enabled for this tailnet
	UsersApprovalOn *bool `json:"usersApprovalOn,omitempty" tf:"users_approval_on,omitempty"`

	// (String) Which user roles are allowed to join external tailnets
	// Which user roles are allowed to join external tailnets
	UsersRoleAllowedToJoinExternalTailnet *string `json:"usersRoleAllowedToJoinExternalTailnet,omitempty" tf:"users_role_allowed_to_join_external_tailnet,omitempty"`
}

type SettingsParameters struct {

	// (String) Link to your external ACL definition or management system. Must be a valid URL.
	// Link to your external ACL definition or management system. Must be a valid URL.
	// +kubebuilder:validation:Optional
	AclsExternalLink *string `json:"aclsExternalLink,omitempty" tf:"acls_external_link,omitempty"`

	// +kubebuilder:validation:Optional
	AclsExternallyManagedOn *bool `json:"aclsExternallyManagedOn,omitempty" tf:"acls_externally_managed_on,omitempty"`

	// (Boolean) Whether device approval is enabled for the tailnet
	// Whether device approval is enabled for the tailnet
	// +kubebuilder:validation:Optional
	DevicesApprovalOn *bool `json:"devicesApprovalOn,omitempty" tf:"devices_approval_on,omitempty"`

	// (Boolean) Whether auto updates are enabled for devices that belong to this tailnet
	// Whether auto updates are enabled for devices that belong to this tailnet
	// +kubebuilder:validation:Optional
	DevicesAutoUpdatesOn *bool `json:"devicesAutoUpdatesOn,omitempty" tf:"devices_auto_updates_on,omitempty"`

	// (Number) The key expiry duration for devices on this tailnet
	// The key expiry duration for devices on this tailnet
	// +kubebuilder:validation:Optional
	DevicesKeyDurationDays *float64 `json:"devicesKeyDurationDays,omitempty" tf:"devices_key_duration_days,omitempty"`

	// (Boolean) Whether provisioning of HTTPS certificates is enabled for the tailnet
	// Whether provisioning of HTTPS certificates is enabled for the tailnet
	// +kubebuilder:validation:Optional
	HTTPSEnabled *bool `json:"httpsEnabled,omitempty" tf:"https_enabled,omitempty"`

	// (Boolean) Whether network flow logs are enabled for the tailnet
	// Whether network flow logs are enabled for the tailnet
	// +kubebuilder:validation:Optional
	NetworkFlowLoggingOn *bool `json:"networkFlowLoggingOn,omitempty" tf:"network_flow_logging_on,omitempty"`

	// (Boolean) Whether identity collection is enabled for device posture integrations for the tailnet
	// Whether identity collection is enabled for device posture integrations for the tailnet
	// +kubebuilder:validation:Optional
	PostureIdentityCollectionOn *bool `json:"postureIdentityCollectionOn,omitempty" tf:"posture_identity_collection_on,omitempty"`

	// (Boolean) Whether regional routing is enabled for the tailnet
	// Whether regional routing is enabled for the tailnet
	// +kubebuilder:validation:Optional
	RegionalRoutingOn *bool `json:"regionalRoutingOn,omitempty" tf:"regional_routing_on,omitempty"`

	// (Boolean) Whether user approval is enabled for this tailnet
	// Whether user approval is enabled for this tailnet
	// +kubebuilder:validation:Optional
	UsersApprovalOn *bool `json:"usersApprovalOn,omitempty" tf:"users_approval_on,omitempty"`

	// (String) Which user roles are allowed to join external tailnets
	// Which user roles are allowed to join external tailnets
	// +kubebuilder:validation:Optional
	UsersRoleAllowedToJoinExternalTailnet *string `json:"usersRoleAllowedToJoinExternalTailnet,omitempty" tf:"users_role_allowed_to_join_external_tailnet,omitempty"`
}

// SettingsSpec defines the desired state of Settings
type SettingsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SettingsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SettingsInitParameters `json:"initProvider,omitempty"`
}

// SettingsStatus defines the observed state of Settings.
type SettingsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SettingsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Settings is the Schema for the Settingss API. The tailnet_settings resource allows you to configure settings for your tailnet. See https://tailscale.com/api#tag/tailnetsettings for more information.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,tailscale}
type Settings struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              SettingsSpec   `json:"spec"`
	Status            SettingsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SettingsList contains a list of Settingss
type SettingsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Settings `json:"items"`
}

// Repository type metadata.
var (
	Settings_Kind             = "Settings"
	Settings_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Settings_Kind}.String()
	Settings_KindAPIVersion   = Settings_Kind + "." + CRDGroupVersion.String()
	Settings_GroupVersionKind = CRDGroupVersion.WithKind(Settings_Kind)
)

func init() {
	SchemeBuilder.Register(&Settings{}, &SettingsList{})
}
