// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Configuration) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Nameservers) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Preferences) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SearchPaths) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SplitNameservers) Hub() {}
