apiVersion: device.tailscale.m.buttah-cloud.io/v1alpha1
kind: Tags
metadata:
  annotations:
    meta.upbound.io/example-id: device/v1alpha1/tags
  labels:
    testing.upbound.io/example-name: sample_tags
  name: sample-tags
  namespace: crossplane-system
spec:
  forProvider:
    deviceId: ${data.tailscale_device.sample_device.node_id}
    tags:
    - room:bedroom
