// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ConfigurationInitParameters struct {

	// (Boolean) Whether or not to enable MagicDNS. Defaults to true.
	// Whether or not to enable MagicDNS. Defaults to true.
	MagicDNS *bool `json:"magicDns,omitempty" tf:"magic_dns,omitempty"`

	// (Block List) Set the nameservers used by devices on your network to resolve DNS queries. override_local_dns must also be true to prefer these nameservers over local DNS configuration. (see below for nested schema)
	// Set the nameservers used by devices on your network to resolve DNS queries. `override_local_dns` must also be true to prefer these nameservers over local DNS configuration.
	Nameservers []NameserversInitParameters `json:"nameservers,omitempty" tf:"nameservers,omitempty"`

	// (Boolean) When enabled, use the configured DNS servers in nameservers to resolve names outside the tailnet. When disabled, devices will prefer their local DNS configuration. Defaults to false.
	// When enabled, use the configured DNS servers in `nameservers` to resolve names outside the tailnet. When disabled, devices will prefer their local DNS configuration. Defaults to false.
	OverrideLocalDNS *bool `json:"overrideLocalDns,omitempty" tf:"override_local_dns,omitempty"`

	// (List of String) Additional search domains. When MagicDNS is on, the tailnet domain is automatically included as the first search domain.
	// Additional search domains. When MagicDNS is on, the tailnet domain is automatically included as the first search domain.
	SearchPaths []*string `json:"searchPaths,omitempty" tf:"search_paths,omitempty"`

	// (Block List) Set the nameservers used by devices on your network to resolve DNS queries on specific domains (requires Tailscale v1.8 or later). Configuration does not depend on override_local_dns. (see below for nested schema)
	// Set the nameservers used by devices on your network to resolve DNS queries on specific domains (requires Tailscale v1.8 or later). Configuration does not depend on `override_local_dns`.
	SplitDNS []SplitDNSInitParameters `json:"splitDns,omitempty" tf:"split_dns,omitempty"`
}

type ConfigurationObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Whether or not to enable MagicDNS. Defaults to true.
	// Whether or not to enable MagicDNS. Defaults to true.
	MagicDNS *bool `json:"magicDns,omitempty" tf:"magic_dns,omitempty"`

	// (Block List) Set the nameservers used by devices on your network to resolve DNS queries. override_local_dns must also be true to prefer these nameservers over local DNS configuration. (see below for nested schema)
	// Set the nameservers used by devices on your network to resolve DNS queries. `override_local_dns` must also be true to prefer these nameservers over local DNS configuration.
	Nameservers []NameserversObservation `json:"nameservers,omitempty" tf:"nameservers,omitempty"`

	// (Boolean) When enabled, use the configured DNS servers in nameservers to resolve names outside the tailnet. When disabled, devices will prefer their local DNS configuration. Defaults to false.
	// When enabled, use the configured DNS servers in `nameservers` to resolve names outside the tailnet. When disabled, devices will prefer their local DNS configuration. Defaults to false.
	OverrideLocalDNS *bool `json:"overrideLocalDns,omitempty" tf:"override_local_dns,omitempty"`

	// (List of String) Additional search domains. When MagicDNS is on, the tailnet domain is automatically included as the first search domain.
	// Additional search domains. When MagicDNS is on, the tailnet domain is automatically included as the first search domain.
	SearchPaths []*string `json:"searchPaths,omitempty" tf:"search_paths,omitempty"`

	// (Block List) Set the nameservers used by devices on your network to resolve DNS queries on specific domains (requires Tailscale v1.8 or later). Configuration does not depend on override_local_dns. (see below for nested schema)
	// Set the nameservers used by devices on your network to resolve DNS queries on specific domains (requires Tailscale v1.8 or later). Configuration does not depend on `override_local_dns`.
	SplitDNS []SplitDNSObservation `json:"splitDns,omitempty" tf:"split_dns,omitempty"`
}

type ConfigurationParameters struct {

	// (Boolean) Whether or not to enable MagicDNS. Defaults to true.
	// Whether or not to enable MagicDNS. Defaults to true.
	// +kubebuilder:validation:Optional
	MagicDNS *bool `json:"magicDns,omitempty" tf:"magic_dns,omitempty"`

	// (Block List) Set the nameservers used by devices on your network to resolve DNS queries. override_local_dns must also be true to prefer these nameservers over local DNS configuration. (see below for nested schema)
	// Set the nameservers used by devices on your network to resolve DNS queries. `override_local_dns` must also be true to prefer these nameservers over local DNS configuration.
	// +kubebuilder:validation:Optional
	Nameservers []NameserversParameters `json:"nameservers,omitempty" tf:"nameservers,omitempty"`

	// (Boolean) When enabled, use the configured DNS servers in nameservers to resolve names outside the tailnet. When disabled, devices will prefer their local DNS configuration. Defaults to false.
	// When enabled, use the configured DNS servers in `nameservers` to resolve names outside the tailnet. When disabled, devices will prefer their local DNS configuration. Defaults to false.
	// +kubebuilder:validation:Optional
	OverrideLocalDNS *bool `json:"overrideLocalDns,omitempty" tf:"override_local_dns,omitempty"`

	// (List of String) Additional search domains. When MagicDNS is on, the tailnet domain is automatically included as the first search domain.
	// Additional search domains. When MagicDNS is on, the tailnet domain is automatically included as the first search domain.
	// +kubebuilder:validation:Optional
	SearchPaths []*string `json:"searchPaths,omitempty" tf:"search_paths,omitempty"`

	// (Block List) Set the nameservers used by devices on your network to resolve DNS queries on specific domains (requires Tailscale v1.8 or later). Configuration does not depend on override_local_dns. (see below for nested schema)
	// Set the nameservers used by devices on your network to resolve DNS queries on specific domains (requires Tailscale v1.8 or later). Configuration does not depend on `override_local_dns`.
	// +kubebuilder:validation:Optional
	SplitDNS []SplitDNSParameters `json:"splitDns,omitempty" tf:"split_dns,omitempty"`
}

type NameserversInitParameters struct {

	// (String) The nameserver's IPv4 or IPv6 address
	// The nameserver's IPv4 or IPv6 address
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// (Boolean) This nameserver will continue to be used when an exit node is selected (requires Tailscale v1.88.1 or later). Defaults to false.
	// This nameserver will continue to be used when an exit node is selected (requires Tailscale v1.88.1 or later). Defaults to false.
	UseWithExitNode *bool `json:"useWithExitNode,omitempty" tf:"use_with_exit_node,omitempty"`
}

type NameserversObservation struct {

	// (String) The nameserver's IPv4 or IPv6 address
	// The nameserver's IPv4 or IPv6 address
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// (Boolean) This nameserver will continue to be used when an exit node is selected (requires Tailscale v1.88.1 or later). Defaults to false.
	// This nameserver will continue to be used when an exit node is selected (requires Tailscale v1.88.1 or later). Defaults to false.
	UseWithExitNode *bool `json:"useWithExitNode,omitempty" tf:"use_with_exit_node,omitempty"`
}

type NameserversParameters struct {

	// (String) The nameserver's IPv4 or IPv6 address
	// The nameserver's IPv4 or IPv6 address
	// +kubebuilder:validation:Optional
	Address *string `json:"address" tf:"address,omitempty"`

	// (Boolean) This nameserver will continue to be used when an exit node is selected (requires Tailscale v1.88.1 or later). Defaults to false.
	// This nameserver will continue to be used when an exit node is selected (requires Tailscale v1.88.1 or later). Defaults to false.
	// +kubebuilder:validation:Optional
	UseWithExitNode *bool `json:"useWithExitNode,omitempty" tf:"use_with_exit_node,omitempty"`
}

type SplitDNSInitParameters struct {

	// (String) The nameservers will be used only for this domain.
	// The nameservers will be used only for this domain.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// (Block List) Set the nameservers used by devices on your network to resolve DNS queries. override_local_dns must also be true to prefer these nameservers over local DNS configuration. (see below for nested schema)
	// Set the nameservers used by devices on your network to resolve DNS queries.
	Nameservers []SplitDNSNameserversInitParameters `json:"nameservers,omitempty" tf:"nameservers,omitempty"`
}

type SplitDNSNameserversInitParameters struct {

	// (String) The nameserver's IPv4 or IPv6 address
	// The nameserver's IPv4 or IPv6 address.
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// (Boolean) This nameserver will continue to be used when an exit node is selected (requires Tailscale v1.88.1 or later). Defaults to false.
	// This nameserver will continue to be used when an exit node is selected (requires Tailscale v1.88.1 or later). Defaults to false.
	UseWithExitNode *bool `json:"useWithExitNode,omitempty" tf:"use_with_exit_node,omitempty"`
}

type SplitDNSNameserversObservation struct {

	// (String) The nameserver's IPv4 or IPv6 address
	// The nameserver's IPv4 or IPv6 address.
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// (Boolean) This nameserver will continue to be used when an exit node is selected (requires Tailscale v1.88.1 or later). Defaults to false.
	// This nameserver will continue to be used when an exit node is selected (requires Tailscale v1.88.1 or later). Defaults to false.
	UseWithExitNode *bool `json:"useWithExitNode,omitempty" tf:"use_with_exit_node,omitempty"`
}

type SplitDNSNameserversParameters struct {

	// (String) The nameserver's IPv4 or IPv6 address
	// The nameserver's IPv4 or IPv6 address.
	// +kubebuilder:validation:Optional
	Address *string `json:"address" tf:"address,omitempty"`

	// (Boolean) This nameserver will continue to be used when an exit node is selected (requires Tailscale v1.88.1 or later). Defaults to false.
	// This nameserver will continue to be used when an exit node is selected (requires Tailscale v1.88.1 or later). Defaults to false.
	// +kubebuilder:validation:Optional
	UseWithExitNode *bool `json:"useWithExitNode,omitempty" tf:"use_with_exit_node,omitempty"`
}

type SplitDNSObservation struct {

	// (String) The nameservers will be used only for this domain.
	// The nameservers will be used only for this domain.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// (Block List) Set the nameservers used by devices on your network to resolve DNS queries. override_local_dns must also be true to prefer these nameservers over local DNS configuration. (see below for nested schema)
	// Set the nameservers used by devices on your network to resolve DNS queries.
	Nameservers []SplitDNSNameserversObservation `json:"nameservers,omitempty" tf:"nameservers,omitempty"`
}

type SplitDNSParameters struct {

	// (String) The nameservers will be used only for this domain.
	// The nameservers will be used only for this domain.
	// +kubebuilder:validation:Optional
	Domain *string `json:"domain" tf:"domain,omitempty"`

	// (Block List) Set the nameservers used by devices on your network to resolve DNS queries. override_local_dns must also be true to prefer these nameservers over local DNS configuration. (see below for nested schema)
	// Set the nameservers used by devices on your network to resolve DNS queries.
	// +kubebuilder:validation:Optional
	Nameservers []SplitDNSNameserversParameters `json:"nameservers,omitempty" tf:"nameservers,omitempty"`
}

// ConfigurationSpec defines the desired state of Configuration
type ConfigurationSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ConfigurationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ConfigurationInitParameters `json:"initProvider,omitempty"`
}

// ConfigurationStatus defines the observed state of Configuration.
type ConfigurationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ConfigurationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Configuration is the Schema for the Configurations API. The dns_configuration resource allows you to manage the complete DNS configuration for your Tailscale network. See https://tailscale.com/kb/1054/dns for more information.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,tailscale}
type Configuration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ConfigurationSpec   `json:"spec"`
	Status            ConfigurationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ConfigurationList contains a list of Configurations
type ConfigurationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Configuration `json:"items"`
}

// Repository type metadata.
var (
	Configuration_Kind             = "Configuration"
	Configuration_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Configuration_Kind}.String()
	Configuration_KindAPIVersion   = Configuration_Kind + "." + CRDGroupVersion.String()
	Configuration_GroupVersionKind = CRDGroupVersion.WithKind(Configuration_Kind)
)

func init() {
	SchemeBuilder.Register(&Configuration{}, &ConfigurationList{})
}
