// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type NameserversInitParameters_2 struct {

	// (List of String) Devices on your network will use these nameservers to resolve DNS names. IPv4 or IPv6 addresses are accepted.
	// Devices on your network will use these nameservers to resolve DNS names. IPv4 or IPv6 addresses are accepted.
	Nameservers []*string `json:"nameservers,omitempty" tf:"nameservers,omitempty"`
}

type NameserversObservation_2 struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (List of String) Devices on your network will use these nameservers to resolve DNS names. IPv4 or IPv6 addresses are accepted.
	// Devices on your network will use these nameservers to resolve DNS names. IPv4 or IPv6 addresses are accepted.
	Nameservers []*string `json:"nameservers,omitempty" tf:"nameservers,omitempty"`
}

type NameserversParameters_2 struct {

	// (List of String) Devices on your network will use these nameservers to resolve DNS names. IPv4 or IPv6 addresses are accepted.
	// Devices on your network will use these nameservers to resolve DNS names. IPv4 or IPv6 addresses are accepted.
	// +kubebuilder:validation:Optional
	Nameservers []*string `json:"nameservers,omitempty" tf:"nameservers,omitempty"`
}

// NameserversSpec defines the desired state of Nameservers
type NameserversSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            NameserversParameters_2 `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NameserversInitParameters_2 `json:"initProvider,omitempty"`
}

// NameserversStatus defines the observed state of Nameservers.
type NameserversStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NameserversObservation_2 `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Nameservers is the Schema for the Nameserverss API. The dns_nameservers resource allows you to configure DNS nameservers for your Tailscale network. See https://tailscale.com/kb/1054/dns for more information.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,tailscale}
type Nameservers struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.nameservers) || (has(self.initProvider) && has(self.initProvider.nameservers))",message="spec.forProvider.nameservers is a required parameter"
	Spec   NameserversSpec   `json:"spec"`
	Status NameserversStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NameserversList contains a list of Nameserverss
type NameserversList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Nameservers `json:"items"`
}

// Repository type metadata.
var (
	Nameservers_Kind             = "Nameservers"
	Nameservers_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Nameservers_Kind}.String()
	Nameservers_KindAPIVersion   = Nameservers_Kind + "." + CRDGroupVersion.String()
	Nameservers_GroupVersionKind = CRDGroupVersion.WithKind(Nameservers_Kind)
)

func init() {
	SchemeBuilder.Register(&Nameservers{}, &NameserversList{})
}
