apiVersion: tailnet.tailscale.m.buttah-cloud.io/v1alpha1
kind: Settings
metadata:
  annotations:
    meta.upbound.io/example-id: tailnet/v1alpha1/settings
  labels:
    testing.upbound.io/example-name: sample_tailnet_settings
  name: sample-tailnet-settings
  namespace: crossplane-system
spec:
  forProvider:
    aclsExternalLink: https://github.com/octocat/Hello-World
    aclsExternallyManagedOn: true
    devicesApprovalOn: true
    devicesAutoUpdatesOn: true
    devicesKeyDurationDays: 5
    httpsEnabled: true
    postureIdentityCollectionOn: true
    usersApprovalOn: true
    usersRoleAllowedToJoinExternalTailnet: member
