//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Configuration) DeepCopyInto(out *Configuration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Configuration.
func (in *Configuration) DeepCopy() *Configuration {
	if in == nil {
		return nil
	}
	out := new(Configuration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Configuration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationInitParameters) DeepCopyInto(out *ConfigurationInitParameters) {
	*out = *in
	if in.CompressionFormat != nil {
		in, out := &in.CompressionFormat, &out.CompressionFormat
		*out = new(string)
		**out = **in
	}
	if in.DestinationType != nil {
		in, out := &in.DestinationType, &out.DestinationType
		*out = new(string)
		**out = **in
	}
	if in.GcsBucket != nil {
		in, out := &in.GcsBucket, &out.GcsBucket
		*out = new(string)
		**out = **in
	}
	if in.GcsCredentials != nil {
		in, out := &in.GcsCredentials, &out.GcsCredentials
		*out = new(string)
		**out = **in
	}
	if in.GcsKeyPrefix != nil {
		in, out := &in.GcsKeyPrefix, &out.GcsKeyPrefix
		*out = new(string)
		**out = **in
	}
	if in.GcsScopes != nil {
		in, out := &in.GcsScopes, &out.GcsScopes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.LogType != nil {
		in, out := &in.LogType, &out.LogType
		*out = new(string)
		**out = **in
	}
	if in.S3AccessKeyID != nil {
		in, out := &in.S3AccessKeyID, &out.S3AccessKeyID
		*out = new(string)
		**out = **in
	}
	if in.S3AuthenticationType != nil {
		in, out := &in.S3AuthenticationType, &out.S3AuthenticationType
		*out = new(string)
		**out = **in
	}
	if in.S3Bucket != nil {
		in, out := &in.S3Bucket, &out.S3Bucket
		*out = new(string)
		**out = **in
	}
	if in.S3ExternalID != nil {
		in, out := &in.S3ExternalID, &out.S3ExternalID
		*out = new(string)
		**out = **in
	}
	if in.S3KeyPrefix != nil {
		in, out := &in.S3KeyPrefix, &out.S3KeyPrefix
		*out = new(string)
		**out = **in
	}
	if in.S3Region != nil {
		in, out := &in.S3Region, &out.S3Region
		*out = new(string)
		**out = **in
	}
	if in.S3RoleArn != nil {
		in, out := &in.S3RoleArn, &out.S3RoleArn
		*out = new(string)
		**out = **in
	}
	if in.S3SecretAccessKeySecretRef != nil {
		in, out := &in.S3SecretAccessKeySecretRef, &out.S3SecretAccessKeySecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.UploadPeriodMinutes != nil {
		in, out := &in.UploadPeriodMinutes, &out.UploadPeriodMinutes
		*out = new(float64)
		**out = **in
	}
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationInitParameters.
func (in *ConfigurationInitParameters) DeepCopy() *ConfigurationInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigurationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationList) DeepCopyInto(out *ConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Configuration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationList.
func (in *ConfigurationList) DeepCopy() *ConfigurationList {
	if in == nil {
		return nil
	}
	out := new(ConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationObservation) DeepCopyInto(out *ConfigurationObservation) {
	*out = *in
	if in.CompressionFormat != nil {
		in, out := &in.CompressionFormat, &out.CompressionFormat
		*out = new(string)
		**out = **in
	}
	if in.DestinationType != nil {
		in, out := &in.DestinationType, &out.DestinationType
		*out = new(string)
		**out = **in
	}
	if in.GcsBucket != nil {
		in, out := &in.GcsBucket, &out.GcsBucket
		*out = new(string)
		**out = **in
	}
	if in.GcsCredentials != nil {
		in, out := &in.GcsCredentials, &out.GcsCredentials
		*out = new(string)
		**out = **in
	}
	if in.GcsKeyPrefix != nil {
		in, out := &in.GcsKeyPrefix, &out.GcsKeyPrefix
		*out = new(string)
		**out = **in
	}
	if in.GcsScopes != nil {
		in, out := &in.GcsScopes, &out.GcsScopes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LogType != nil {
		in, out := &in.LogType, &out.LogType
		*out = new(string)
		**out = **in
	}
	if in.S3AccessKeyID != nil {
		in, out := &in.S3AccessKeyID, &out.S3AccessKeyID
		*out = new(string)
		**out = **in
	}
	if in.S3AuthenticationType != nil {
		in, out := &in.S3AuthenticationType, &out.S3AuthenticationType
		*out = new(string)
		**out = **in
	}
	if in.S3Bucket != nil {
		in, out := &in.S3Bucket, &out.S3Bucket
		*out = new(string)
		**out = **in
	}
	if in.S3ExternalID != nil {
		in, out := &in.S3ExternalID, &out.S3ExternalID
		*out = new(string)
		**out = **in
	}
	if in.S3KeyPrefix != nil {
		in, out := &in.S3KeyPrefix, &out.S3KeyPrefix
		*out = new(string)
		**out = **in
	}
	if in.S3Region != nil {
		in, out := &in.S3Region, &out.S3Region
		*out = new(string)
		**out = **in
	}
	if in.S3RoleArn != nil {
		in, out := &in.S3RoleArn, &out.S3RoleArn
		*out = new(string)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.UploadPeriodMinutes != nil {
		in, out := &in.UploadPeriodMinutes, &out.UploadPeriodMinutes
		*out = new(float64)
		**out = **in
	}
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationObservation.
func (in *ConfigurationObservation) DeepCopy() *ConfigurationObservation {
	if in == nil {
		return nil
	}
	out := new(ConfigurationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationParameters) DeepCopyInto(out *ConfigurationParameters) {
	*out = *in
	if in.CompressionFormat != nil {
		in, out := &in.CompressionFormat, &out.CompressionFormat
		*out = new(string)
		**out = **in
	}
	if in.DestinationType != nil {
		in, out := &in.DestinationType, &out.DestinationType
		*out = new(string)
		**out = **in
	}
	if in.GcsBucket != nil {
		in, out := &in.GcsBucket, &out.GcsBucket
		*out = new(string)
		**out = **in
	}
	if in.GcsCredentials != nil {
		in, out := &in.GcsCredentials, &out.GcsCredentials
		*out = new(string)
		**out = **in
	}
	if in.GcsKeyPrefix != nil {
		in, out := &in.GcsKeyPrefix, &out.GcsKeyPrefix
		*out = new(string)
		**out = **in
	}
	if in.GcsScopes != nil {
		in, out := &in.GcsScopes, &out.GcsScopes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.LogType != nil {
		in, out := &in.LogType, &out.LogType
		*out = new(string)
		**out = **in
	}
	if in.S3AccessKeyID != nil {
		in, out := &in.S3AccessKeyID, &out.S3AccessKeyID
		*out = new(string)
		**out = **in
	}
	if in.S3AuthenticationType != nil {
		in, out := &in.S3AuthenticationType, &out.S3AuthenticationType
		*out = new(string)
		**out = **in
	}
	if in.S3Bucket != nil {
		in, out := &in.S3Bucket, &out.S3Bucket
		*out = new(string)
		**out = **in
	}
	if in.S3ExternalID != nil {
		in, out := &in.S3ExternalID, &out.S3ExternalID
		*out = new(string)
		**out = **in
	}
	if in.S3KeyPrefix != nil {
		in, out := &in.S3KeyPrefix, &out.S3KeyPrefix
		*out = new(string)
		**out = **in
	}
	if in.S3Region != nil {
		in, out := &in.S3Region, &out.S3Region
		*out = new(string)
		**out = **in
	}
	if in.S3RoleArn != nil {
		in, out := &in.S3RoleArn, &out.S3RoleArn
		*out = new(string)
		**out = **in
	}
	if in.S3SecretAccessKeySecretRef != nil {
		in, out := &in.S3SecretAccessKeySecretRef, &out.S3SecretAccessKeySecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.UploadPeriodMinutes != nil {
		in, out := &in.UploadPeriodMinutes, &out.UploadPeriodMinutes
		*out = new(float64)
		**out = **in
	}
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationParameters.
func (in *ConfigurationParameters) DeepCopy() *ConfigurationParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigurationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationSpec) DeepCopyInto(out *ConfigurationSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationSpec.
func (in *ConfigurationSpec) DeepCopy() *ConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationStatus) DeepCopyInto(out *ConfigurationStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationStatus.
func (in *ConfigurationStatus) DeepCopy() *ConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}
