// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package namespaced contains Kubernetes API for the provider.
package namespaced

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/buttahtoast/provider-tailscale/apis/namespaced/aws/v1alpha1"
	v1alpha1device "github.com/buttahtoast/provider-tailscale/apis/namespaced/device/v1alpha1"
	v1alpha1dns "github.com/buttahtoast/provider-tailscale/apis/namespaced/dns/v1alpha1"
	v1alpha1federated "github.com/buttahtoast/provider-tailscale/apis/namespaced/federated/v1alpha1"
	v1alpha1logstream "github.com/buttahtoast/provider-tailscale/apis/namespaced/logstream/v1alpha1"
	v1alpha1oauth "github.com/buttahtoast/provider-tailscale/apis/namespaced/oauth/v1alpha1"
	v1alpha1posture "github.com/buttahtoast/provider-tailscale/apis/namespaced/posture/v1alpha1"
	v1alpha1tailnet "github.com/buttahtoast/provider-tailscale/apis/namespaced/tailnet/v1alpha1"
	v1alpha1tailscale "github.com/buttahtoast/provider-tailscale/apis/namespaced/tailscale/v1alpha1"
	v1alpha1namespaced "github.com/buttahtoast/provider-tailscale/apis/namespaced/v1alpha1"
	v1beta1 "github.com/buttahtoast/provider-tailscale/apis/namespaced/v1beta1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1device.SchemeBuilder.AddToScheme,
		v1alpha1dns.SchemeBuilder.AddToScheme,
		v1alpha1federated.SchemeBuilder.AddToScheme,
		v1alpha1logstream.SchemeBuilder.AddToScheme,
		v1alpha1oauth.SchemeBuilder.AddToScheme,
		v1alpha1posture.SchemeBuilder.AddToScheme,
		v1alpha1tailnet.SchemeBuilder.AddToScheme,
		v1alpha1tailscale.SchemeBuilder.AddToScheme,
		v1alpha1namespaced.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
