// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ConfigurationInitParameters struct {

	// (String) The compression algorithm used for logs. Valid values are none, zstd or gzip. Defaults to none.
	// The compression algorithm used for logs. Valid values are `none`, `zstd` or `gzip`. Defaults to `none`.
	CompressionFormat *string `json:"compressionFormat,omitempty" tf:"compression_format,omitempty"`

	// (String) The type of SIEM platform to stream to. Valid values are axiom, cribl, datadog, elastic, gcs, panther, splunk, and s3.
	// The type of SIEM platform to stream to. Valid values are `axiom`, `cribl`, `datadog`, `elastic`, `gcs`, `panther`, `splunk`, and `s3`.
	DestinationType *string `json:"destinationType,omitempty" tf:"destination_type,omitempty"`

	// (String) The name of the GCS bucket
	// The name of the GCS bucket
	GcsBucket *string `json:"gcsBucket,omitempty" tf:"gcs_bucket,omitempty"`

	// (String) The encoded string of JSON that is used to authenticate for workload identity in GCS
	// The encoded string of JSON that is used to authenticate for workload identity in GCS
	GcsCredentials *string `json:"gcsCredentials,omitempty" tf:"gcs_credentials,omitempty"`

	// (String) The GCS key prefix for the bucket
	// The GCS key prefix for the bucket
	GcsKeyPrefix *string `json:"gcsKeyPrefix,omitempty" tf:"gcs_key_prefix,omitempty"`

	// (Set of String) The GCS scopes needed to be able to write in the bucket
	// The GCS scopes needed to be able to write in the bucket
	// +listType=set
	GcsScopes []*string `json:"gcsScopes,omitempty" tf:"gcs_scopes,omitempty"`

	// (String) The type of logs to stream. Valid values are configuration (configuration audit logs) and network (network flow logs).
	// The type of logs to stream. Valid values are `configuration` (configuration audit logs) and `network` (network flow logs).
	LogType *string `json:"logType,omitempty" tf:"log_type,omitempty"`

	// (String) The S3 access key ID. Required if destination_type is s3 and s3_authentication_type is 'accesskey'.
	// The S3 access key ID. Required if destination_type is s3 and s3_authentication_type is 'accesskey'.
	S3AccessKeyID *string `json:"s3AccessKeyId,omitempty" tf:"s3_access_key_id,omitempty"`

	// (String) The type of authentication to use for S3. Required if destination_type is s3. Valid values are accesskey and rolearn. Tailscale recommends using rolearn.
	// The type of authentication to use for S3. Required if destination_type is `s3`. Valid values are `accesskey` and `rolearn`. Tailscale recommends using `rolearn`.
	S3AuthenticationType *string `json:"s3AuthenticationType,omitempty" tf:"s3_authentication_type,omitempty"`

	// (String) The S3 bucket name. Required if destination_type is 's3'.
	// The S3 bucket name. Required if destination_type is 's3'.
	S3Bucket *string `json:"s3Bucket,omitempty" tf:"s3_bucket,omitempty"`

	// based authentication. Required if destination_type is 's3' and s3_authentication_type is 'rolearn'. This can be obtained via the tailscale_aws_external_id resource.
	// The AWS External ID that Tailscale supplies when authenticating using role-based authentication. Required if destination_type is 's3' and s3_authentication_type is 'rolearn'. This can be obtained via the tailscale_aws_external_id resource.
	S3ExternalID *string `json:"s3ExternalId,omitempty" tf:"s3_external_id,omitempty"`

	// generated S3 key name.
	// An optional S3 key prefix to prepend to the auto-generated S3 key name.
	S3KeyPrefix *string `json:"s3KeyPrefix,omitempty" tf:"s3_key_prefix,omitempty"`

	// (String) The region in which the S3 bucket is located. Required if destination_type is 's3'.
	// The region in which the S3 bucket is located. Required if destination_type is 's3'.
	S3Region *string `json:"s3Region,omitempty" tf:"s3_region,omitempty"`

	// based authentication. Required if destination_type is 's3' and s3_authentication_type is 'rolearn'.
	// ARN of the AWS IAM role that Tailscale should assume when using role-based authentication. Required if destination_type is 's3' and s3_authentication_type is 'rolearn'.
	S3RoleArn *string `json:"s3RoleArn,omitempty" tf:"s3_role_arn,omitempty"`

	// (String, Sensitive) The S3 secret access key. Required if destination_type is 's3' and s3_authentication_type is 'accesskey'.
	// The S3 secret access key. Required if destination_type is 's3' and s3_authentication_type is 'accesskey'.
	S3SecretAccessKeySecretRef *v1.LocalSecretKeySelector `json:"s3SecretAccessKeySecretRef,omitempty" tf:"-"`

	// (String, Sensitive) The token/password with which log streams to this endpoint should be authenticated, required unless destination_type is 's3'.
	// The token/password with which log streams to this endpoint should be authenticated, required unless destination_type is 's3'.
	TokenSecretRef *v1.LocalSecretKeySelector `json:"tokenSecretRef,omitempty" tf:"-"`

	// (String) The URL to which log streams are being posted. If destination_type is 's3' and you want to use the official Amazon S3 endpoint, leave this empty.
	// The URL to which log streams are being posted. If destination_type is 's3' and you want to use the official Amazon S3 endpoint, leave this empty.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// (Number) An optional number of minutes to wait in between uploading new logs. If the quantity of logs does not fit within a single upload, multiple uploads will be made.
	// An optional number of minutes to wait in between uploading new logs. If the quantity of logs does not fit within a single upload, multiple uploads will be made.
	UploadPeriodMinutes *float64 `json:"uploadPeriodMinutes,omitempty" tf:"upload_period_minutes,omitempty"`

	// (String) The username with which log streams to this endpoint are authenticated. Only required if destination_type is 'elastic', defaults to 'user' if not set.
	// The username with which log streams to this endpoint are authenticated. Only required if destination_type is 'elastic', defaults to 'user' if not set.
	User *string `json:"user,omitempty" tf:"user,omitempty"`
}

type ConfigurationObservation struct {

	// (String) The compression algorithm used for logs. Valid values are none, zstd or gzip. Defaults to none.
	// The compression algorithm used for logs. Valid values are `none`, `zstd` or `gzip`. Defaults to `none`.
	CompressionFormat *string `json:"compressionFormat,omitempty" tf:"compression_format,omitempty"`

	// (String) The type of SIEM platform to stream to. Valid values are axiom, cribl, datadog, elastic, gcs, panther, splunk, and s3.
	// The type of SIEM platform to stream to. Valid values are `axiom`, `cribl`, `datadog`, `elastic`, `gcs`, `panther`, `splunk`, and `s3`.
	DestinationType *string `json:"destinationType,omitempty" tf:"destination_type,omitempty"`

	// (String) The name of the GCS bucket
	// The name of the GCS bucket
	GcsBucket *string `json:"gcsBucket,omitempty" tf:"gcs_bucket,omitempty"`

	// (String) The encoded string of JSON that is used to authenticate for workload identity in GCS
	// The encoded string of JSON that is used to authenticate for workload identity in GCS
	GcsCredentials *string `json:"gcsCredentials,omitempty" tf:"gcs_credentials,omitempty"`

	// (String) The GCS key prefix for the bucket
	// The GCS key prefix for the bucket
	GcsKeyPrefix *string `json:"gcsKeyPrefix,omitempty" tf:"gcs_key_prefix,omitempty"`

	// (Set of String) The GCS scopes needed to be able to write in the bucket
	// The GCS scopes needed to be able to write in the bucket
	// +listType=set
	GcsScopes []*string `json:"gcsScopes,omitempty" tf:"gcs_scopes,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The type of logs to stream. Valid values are configuration (configuration audit logs) and network (network flow logs).
	// The type of logs to stream. Valid values are `configuration` (configuration audit logs) and `network` (network flow logs).
	LogType *string `json:"logType,omitempty" tf:"log_type,omitempty"`

	// (String) The S3 access key ID. Required if destination_type is s3 and s3_authentication_type is 'accesskey'.
	// The S3 access key ID. Required if destination_type is s3 and s3_authentication_type is 'accesskey'.
	S3AccessKeyID *string `json:"s3AccessKeyId,omitempty" tf:"s3_access_key_id,omitempty"`

	// (String) The type of authentication to use for S3. Required if destination_type is s3. Valid values are accesskey and rolearn. Tailscale recommends using rolearn.
	// The type of authentication to use for S3. Required if destination_type is `s3`. Valid values are `accesskey` and `rolearn`. Tailscale recommends using `rolearn`.
	S3AuthenticationType *string `json:"s3AuthenticationType,omitempty" tf:"s3_authentication_type,omitempty"`

	// (String) The S3 bucket name. Required if destination_type is 's3'.
	// The S3 bucket name. Required if destination_type is 's3'.
	S3Bucket *string `json:"s3Bucket,omitempty" tf:"s3_bucket,omitempty"`

	// based authentication. Required if destination_type is 's3' and s3_authentication_type is 'rolearn'. This can be obtained via the tailscale_aws_external_id resource.
	// The AWS External ID that Tailscale supplies when authenticating using role-based authentication. Required if destination_type is 's3' and s3_authentication_type is 'rolearn'. This can be obtained via the tailscale_aws_external_id resource.
	S3ExternalID *string `json:"s3ExternalId,omitempty" tf:"s3_external_id,omitempty"`

	// generated S3 key name.
	// An optional S3 key prefix to prepend to the auto-generated S3 key name.
	S3KeyPrefix *string `json:"s3KeyPrefix,omitempty" tf:"s3_key_prefix,omitempty"`

	// (String) The region in which the S3 bucket is located. Required if destination_type is 's3'.
	// The region in which the S3 bucket is located. Required if destination_type is 's3'.
	S3Region *string `json:"s3Region,omitempty" tf:"s3_region,omitempty"`

	// based authentication. Required if destination_type is 's3' and s3_authentication_type is 'rolearn'.
	// ARN of the AWS IAM role that Tailscale should assume when using role-based authentication. Required if destination_type is 's3' and s3_authentication_type is 'rolearn'.
	S3RoleArn *string `json:"s3RoleArn,omitempty" tf:"s3_role_arn,omitempty"`

	// (String) The URL to which log streams are being posted. If destination_type is 's3' and you want to use the official Amazon S3 endpoint, leave this empty.
	// The URL to which log streams are being posted. If destination_type is 's3' and you want to use the official Amazon S3 endpoint, leave this empty.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// (Number) An optional number of minutes to wait in between uploading new logs. If the quantity of logs does not fit within a single upload, multiple uploads will be made.
	// An optional number of minutes to wait in between uploading new logs. If the quantity of logs does not fit within a single upload, multiple uploads will be made.
	UploadPeriodMinutes *float64 `json:"uploadPeriodMinutes,omitempty" tf:"upload_period_minutes,omitempty"`

	// (String) The username with which log streams to this endpoint are authenticated. Only required if destination_type is 'elastic', defaults to 'user' if not set.
	// The username with which log streams to this endpoint are authenticated. Only required if destination_type is 'elastic', defaults to 'user' if not set.
	User *string `json:"user,omitempty" tf:"user,omitempty"`
}

type ConfigurationParameters struct {

	// (String) The compression algorithm used for logs. Valid values are none, zstd or gzip. Defaults to none.
	// The compression algorithm used for logs. Valid values are `none`, `zstd` or `gzip`. Defaults to `none`.
	// +kubebuilder:validation:Optional
	CompressionFormat *string `json:"compressionFormat,omitempty" tf:"compression_format,omitempty"`

	// (String) The type of SIEM platform to stream to. Valid values are axiom, cribl, datadog, elastic, gcs, panther, splunk, and s3.
	// The type of SIEM platform to stream to. Valid values are `axiom`, `cribl`, `datadog`, `elastic`, `gcs`, `panther`, `splunk`, and `s3`.
	// +kubebuilder:validation:Optional
	DestinationType *string `json:"destinationType,omitempty" tf:"destination_type,omitempty"`

	// (String) The name of the GCS bucket
	// The name of the GCS bucket
	// +kubebuilder:validation:Optional
	GcsBucket *string `json:"gcsBucket,omitempty" tf:"gcs_bucket,omitempty"`

	// (String) The encoded string of JSON that is used to authenticate for workload identity in GCS
	// The encoded string of JSON that is used to authenticate for workload identity in GCS
	// +kubebuilder:validation:Optional
	GcsCredentials *string `json:"gcsCredentials,omitempty" tf:"gcs_credentials,omitempty"`

	// (String) The GCS key prefix for the bucket
	// The GCS key prefix for the bucket
	// +kubebuilder:validation:Optional
	GcsKeyPrefix *string `json:"gcsKeyPrefix,omitempty" tf:"gcs_key_prefix,omitempty"`

	// (Set of String) The GCS scopes needed to be able to write in the bucket
	// The GCS scopes needed to be able to write in the bucket
	// +kubebuilder:validation:Optional
	// +listType=set
	GcsScopes []*string `json:"gcsScopes,omitempty" tf:"gcs_scopes,omitempty"`

	// (String) The type of logs to stream. Valid values are configuration (configuration audit logs) and network (network flow logs).
	// The type of logs to stream. Valid values are `configuration` (configuration audit logs) and `network` (network flow logs).
	// +kubebuilder:validation:Optional
	LogType *string `json:"logType,omitempty" tf:"log_type,omitempty"`

	// (String) The S3 access key ID. Required if destination_type is s3 and s3_authentication_type is 'accesskey'.
	// The S3 access key ID. Required if destination_type is s3 and s3_authentication_type is 'accesskey'.
	// +kubebuilder:validation:Optional
	S3AccessKeyID *string `json:"s3AccessKeyId,omitempty" tf:"s3_access_key_id,omitempty"`

	// (String) The type of authentication to use for S3. Required if destination_type is s3. Valid values are accesskey and rolearn. Tailscale recommends using rolearn.
	// The type of authentication to use for S3. Required if destination_type is `s3`. Valid values are `accesskey` and `rolearn`. Tailscale recommends using `rolearn`.
	// +kubebuilder:validation:Optional
	S3AuthenticationType *string `json:"s3AuthenticationType,omitempty" tf:"s3_authentication_type,omitempty"`

	// (String) The S3 bucket name. Required if destination_type is 's3'.
	// The S3 bucket name. Required if destination_type is 's3'.
	// +kubebuilder:validation:Optional
	S3Bucket *string `json:"s3Bucket,omitempty" tf:"s3_bucket,omitempty"`

	// based authentication. Required if destination_type is 's3' and s3_authentication_type is 'rolearn'. This can be obtained via the tailscale_aws_external_id resource.
	// The AWS External ID that Tailscale supplies when authenticating using role-based authentication. Required if destination_type is 's3' and s3_authentication_type is 'rolearn'. This can be obtained via the tailscale_aws_external_id resource.
	// +kubebuilder:validation:Optional
	S3ExternalID *string `json:"s3ExternalId,omitempty" tf:"s3_external_id,omitempty"`

	// generated S3 key name.
	// An optional S3 key prefix to prepend to the auto-generated S3 key name.
	// +kubebuilder:validation:Optional
	S3KeyPrefix *string `json:"s3KeyPrefix,omitempty" tf:"s3_key_prefix,omitempty"`

	// (String) The region in which the S3 bucket is located. Required if destination_type is 's3'.
	// The region in which the S3 bucket is located. Required if destination_type is 's3'.
	// +kubebuilder:validation:Optional
	S3Region *string `json:"s3Region,omitempty" tf:"s3_region,omitempty"`

	// based authentication. Required if destination_type is 's3' and s3_authentication_type is 'rolearn'.
	// ARN of the AWS IAM role that Tailscale should assume when using role-based authentication. Required if destination_type is 's3' and s3_authentication_type is 'rolearn'.
	// +kubebuilder:validation:Optional
	S3RoleArn *string `json:"s3RoleArn,omitempty" tf:"s3_role_arn,omitempty"`

	// (String, Sensitive) The S3 secret access key. Required if destination_type is 's3' and s3_authentication_type is 'accesskey'.
	// The S3 secret access key. Required if destination_type is 's3' and s3_authentication_type is 'accesskey'.
	// +kubebuilder:validation:Optional
	S3SecretAccessKeySecretRef *v1.LocalSecretKeySelector `json:"s3SecretAccessKeySecretRef,omitempty" tf:"-"`

	// (String, Sensitive) The token/password with which log streams to this endpoint should be authenticated, required unless destination_type is 's3'.
	// The token/password with which log streams to this endpoint should be authenticated, required unless destination_type is 's3'.
	// +kubebuilder:validation:Optional
	TokenSecretRef *v1.LocalSecretKeySelector `json:"tokenSecretRef,omitempty" tf:"-"`

	// (String) The URL to which log streams are being posted. If destination_type is 's3' and you want to use the official Amazon S3 endpoint, leave this empty.
	// The URL to which log streams are being posted. If destination_type is 's3' and you want to use the official Amazon S3 endpoint, leave this empty.
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// (Number) An optional number of minutes to wait in between uploading new logs. If the quantity of logs does not fit within a single upload, multiple uploads will be made.
	// An optional number of minutes to wait in between uploading new logs. If the quantity of logs does not fit within a single upload, multiple uploads will be made.
	// +kubebuilder:validation:Optional
	UploadPeriodMinutes *float64 `json:"uploadPeriodMinutes,omitempty" tf:"upload_period_minutes,omitempty"`

	// (String) The username with which log streams to this endpoint are authenticated. Only required if destination_type is 'elastic', defaults to 'user' if not set.
	// The username with which log streams to this endpoint are authenticated. Only required if destination_type is 'elastic', defaults to 'user' if not set.
	// +kubebuilder:validation:Optional
	User *string `json:"user,omitempty" tf:"user,omitempty"`
}

// ConfigurationSpec defines the desired state of Configuration
type ConfigurationSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ConfigurationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ConfigurationInitParameters `json:"initProvider,omitempty"`
}

// ConfigurationStatus defines the observed state of Configuration.
type ConfigurationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ConfigurationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Configuration is the Schema for the Configurations API. The logstream_configuration resource allows you to configure streaming configuration or network flow logs to a supported security information and event management (SIEM) system. See https://tailscale.com/kb/1255/log-streaming for more information.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,tailscale}
type Configuration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.destinationType) || (has(self.initProvider) && has(self.initProvider.destinationType))",message="spec.forProvider.destinationType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.logType) || (has(self.initProvider) && has(self.initProvider.logType))",message="spec.forProvider.logType is a required parameter"
	Spec   ConfigurationSpec   `json:"spec"`
	Status ConfigurationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ConfigurationList contains a list of Configurations
type ConfigurationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Configuration `json:"items"`
}

// Repository type metadata.
var (
	Configuration_Kind             = "Configuration"
	Configuration_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Configuration_Kind}.String()
	Configuration_KindAPIVersion   = Configuration_Kind + "." + CRDGroupVersion.String()
	Configuration_GroupVersionKind = CRDGroupVersion.WithKind(Configuration_Kind)
)

func init() {
	SchemeBuilder.Register(&Configuration{}, &ConfigurationList{})
}
