// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AccountInitParameters struct {

	// (String) Email address to send communications to
	// Email address to send communications to
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type AccountObservation struct {

	// (String) Email address to send communications to
	// Email address to send communications to
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type AccountParameters struct {

	// (String) Email address to send communications to
	// Email address to send communications to
	// +kubebuilder:validation:Optional
	Email *string `json:"email" tf:"email,omitempty"`
}

type ContactsInitParameters struct {

	// (Block Set) Configuration for communications about important changes to your tailnet (see below for nested schema)
	// Configuration for communications about important changes to your tailnet
	Account []AccountInitParameters `json:"account,omitempty" tf:"account,omitempty"`

	// (Block Set) Configuration for communications about security issues affecting your tailnet (see below for nested schema)
	// Configuration for communications about security issues affecting your tailnet
	Security []SecurityInitParameters `json:"security,omitempty" tf:"security,omitempty"`

	// (Block Set) Configuration for communications about misconfigurations in your tailnet (see below for nested schema)
	// Configuration for communications about misconfigurations in your tailnet
	Support []SupportInitParameters `json:"support,omitempty" tf:"support,omitempty"`
}

type ContactsObservation struct {

	// (Block Set) Configuration for communications about important changes to your tailnet (see below for nested schema)
	// Configuration for communications about important changes to your tailnet
	Account []AccountObservation `json:"account,omitempty" tf:"account,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Block Set) Configuration for communications about security issues affecting your tailnet (see below for nested schema)
	// Configuration for communications about security issues affecting your tailnet
	Security []SecurityObservation `json:"security,omitempty" tf:"security,omitempty"`

	// (Block Set) Configuration for communications about misconfigurations in your tailnet (see below for nested schema)
	// Configuration for communications about misconfigurations in your tailnet
	Support []SupportObservation `json:"support,omitempty" tf:"support,omitempty"`
}

type ContactsParameters struct {

	// (Block Set) Configuration for communications about important changes to your tailnet (see below for nested schema)
	// Configuration for communications about important changes to your tailnet
	// +kubebuilder:validation:Optional
	Account []AccountParameters `json:"account,omitempty" tf:"account,omitempty"`

	// (Block Set) Configuration for communications about security issues affecting your tailnet (see below for nested schema)
	// Configuration for communications about security issues affecting your tailnet
	// +kubebuilder:validation:Optional
	Security []SecurityParameters `json:"security,omitempty" tf:"security,omitempty"`

	// (Block Set) Configuration for communications about misconfigurations in your tailnet (see below for nested schema)
	// Configuration for communications about misconfigurations in your tailnet
	// +kubebuilder:validation:Optional
	Support []SupportParameters `json:"support,omitempty" tf:"support,omitempty"`
}

type SecurityInitParameters struct {

	// (String) Email address to send communications to
	// Email address to send communications to
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type SecurityObservation struct {

	// (String) Email address to send communications to
	// Email address to send communications to
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type SecurityParameters struct {

	// (String) Email address to send communications to
	// Email address to send communications to
	// +kubebuilder:validation:Optional
	Email *string `json:"email" tf:"email,omitempty"`
}

type SupportInitParameters struct {

	// (String) Email address to send communications to
	// Email address to send communications to
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type SupportObservation struct {

	// (String) Email address to send communications to
	// Email address to send communications to
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type SupportParameters struct {

	// (String) Email address to send communications to
	// Email address to send communications to
	// +kubebuilder:validation:Optional
	Email *string `json:"email" tf:"email,omitempty"`
}

// ContactsSpec defines the desired state of Contacts
type ContactsSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ContactsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ContactsInitParameters `json:"initProvider,omitempty"`
}

// ContactsStatus defines the observed state of Contacts.
type ContactsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ContactsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Contacts is the Schema for the Contactss API. The contacts resource allows you to configure contact details for your Tailscale network. See https://tailscale.com/kb/1224/contact-preferences for more information.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,tailscale}
type Contacts struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ContactsSpec   `json:"spec"`
	Status            ContactsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ContactsList contains a list of Contactss
type ContactsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Contacts `json:"items"`
}

// Repository type metadata.
var (
	Contacts_Kind             = "Contacts"
	Contacts_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Contacts_Kind}.String()
	Contacts_KindAPIVersion   = Contacts_Kind + "." + CRDGroupVersion.String()
	Contacts_GroupVersionKind = CRDGroupVersion.WithKind(Contacts_Kind)
)

func init() {
	SchemeBuilder.Register(&Contacts{}, &ContactsList{})
}
