// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type SubnetRoutesInitParameters struct {

	// (String) The device to set subnet routes for
	// The device to set subnet routes for
	DeviceID *string `json:"deviceId,omitempty" tf:"device_id,omitempty"`

	// (Set of String) The subnet routes that are enabled to be routed by a device
	// The subnet routes that are enabled to be routed by a device
	// +listType=set
	Routes []*string `json:"routes,omitempty" tf:"routes,omitempty"`
}

type SubnetRoutesObservation struct {

	// (String) The device to set subnet routes for
	// The device to set subnet routes for
	DeviceID *string `json:"deviceId,omitempty" tf:"device_id,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Set of String) The subnet routes that are enabled to be routed by a device
	// The subnet routes that are enabled to be routed by a device
	// +listType=set
	Routes []*string `json:"routes,omitempty" tf:"routes,omitempty"`
}

type SubnetRoutesParameters struct {

	// (String) The device to set subnet routes for
	// The device to set subnet routes for
	// +kubebuilder:validation:Optional
	DeviceID *string `json:"deviceId,omitempty" tf:"device_id,omitempty"`

	// (Set of String) The subnet routes that are enabled to be routed by a device
	// The subnet routes that are enabled to be routed by a device
	// +kubebuilder:validation:Optional
	// +listType=set
	Routes []*string `json:"routes,omitempty" tf:"routes,omitempty"`
}

// SubnetRoutesSpec defines the desired state of SubnetRoutes
type SubnetRoutesSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SubnetRoutesParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SubnetRoutesInitParameters `json:"initProvider,omitempty"`
}

// SubnetRoutesStatus defines the observed state of SubnetRoutes.
type SubnetRoutesStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SubnetRoutesObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SubnetRoutes is the Schema for the SubnetRoutess API. The device_subnet_routes resource allows you to configure enabled subnet routes for your Tailscale devices. See https://tailscale.com/kb/1019/subnets for more information. Routes must be both advertised and enabled for a device to act as a subnet router or exit node. If a device is advertising routes, they are not exposed to traffic until they are enabled. Conversely, if routes are enabled before they are advertised, they are not available for routing until the device in question is advertising them. Note: all routes enabled for the device through the admin console or autoApprovers in the ACL must be explicitly added to the routes attribute of this resource to avoid configuration drift.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,tailscale}
type SubnetRoutes struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.deviceId) || (has(self.initProvider) && has(self.initProvider.deviceId))",message="spec.forProvider.deviceId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.routes) || (has(self.initProvider) && has(self.initProvider.routes))",message="spec.forProvider.routes is a required parameter"
	Spec   SubnetRoutesSpec   `json:"spec"`
	Status SubnetRoutesStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SubnetRoutesList contains a list of SubnetRoutess
type SubnetRoutesList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SubnetRoutes `json:"items"`
}

// Repository type metadata.
var (
	SubnetRoutes_Kind             = "SubnetRoutes"
	SubnetRoutes_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SubnetRoutes_Kind}.String()
	SubnetRoutes_KindAPIVersion   = SubnetRoutes_Kind + "." + CRDGroupVersion.String()
	SubnetRoutes_GroupVersionKind = CRDGroupVersion.WithKind(SubnetRoutes_Kind)
)

func init() {
	SchemeBuilder.Register(&SubnetRoutes{}, &SubnetRoutesList{})
}
