// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type IdentityInitParameters struct {

	// (String) The value used when matching against the aud claim from an OIDC identity token. Specifying the audience is optional as Tailscale will generate a secure audience at creation time by default.   It is recommended to let Tailscale generate the audience unless the identity provider you are integrating with requires a specific audience format.
	// The value used when matching against the `aud` claim from an OIDC identity token. Specifying the audience is optional as Tailscale will generate a secure audience at creation time by default.   It is recommended to let Tailscale generate the audience unless the identity provider you are integrating with requires a specific audience format.
	Audience *string `json:"audience,omitempty" tf:"audience,omitempty"`

	// (Map of String) A map of claim names to pattern strings used to match against arbitrary claims in the OIDC identity token. Patterns can include * characters to match against any character.
	// A map of claim names to pattern strings used to match against arbitrary claims in the OIDC identity token. Patterns can include `*` characters to match against any character.
	// +mapType=granular
	CustomClaimRules map[string]*string `json:"customClaimRules,omitempty" tf:"custom_claim_rules,omitempty"`

	// (String) A description of the federated identity consisting of alphanumeric characters. Defaults to "".
	// A description of the federated identity consisting of alphanumeric characters. Defaults to `""`.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The issuer of the OIDC identity token used in the token exchange. Must be a valid and publicly reachable https:// URL.
	// The issuer of the OIDC identity token used in the token exchange. Must be a valid and publicly reachable https:// URL.
	Issuer *string `json:"issuer,omitempty" tf:"issuer,omitempty"`

	// (Set of String) Scopes to grant to the federated identity. See https://tailscale.com/kb/1623/ for a list of available scopes.
	// Scopes to grant to the federated identity. See https://tailscale.com/kb/1623/ for a list of available scopes.
	// +listType=set
	Scopes []*string `json:"scopes,omitempty" tf:"scopes,omitempty"`

	// (String) The pattern used when matching against the sub claim from an OIDC identity token. Patterns can include * characters to match against any character.
	// The pattern used when matching against the `sub` claim from an OIDC identity token. Patterns can include `*` characters to match against any character.
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`

	// (Set of String) A list of tags that access tokens generated for the federated identity will be able to assign to devices. Mandatory if the scopes include "devices:core" or "auth_keys".
	// A list of tags that access tokens generated for the federated identity will be able to assign to devices. Mandatory if the scopes include "devices:core" or "auth_keys".
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type IdentityObservation struct {

	// (String) The value used when matching against the aud claim from an OIDC identity token. Specifying the audience is optional as Tailscale will generate a secure audience at creation time by default.   It is recommended to let Tailscale generate the audience unless the identity provider you are integrating with requires a specific audience format.
	// The value used when matching against the `aud` claim from an OIDC identity token. Specifying the audience is optional as Tailscale will generate a secure audience at creation time by default.   It is recommended to let Tailscale generate the audience unless the identity provider you are integrating with requires a specific audience format.
	Audience *string `json:"audience,omitempty" tf:"audience,omitempty"`

	// (String) The creation timestamp of the key in RFC3339 format
	// The creation timestamp of the key in RFC3339 format
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (Map of String) A map of claim names to pattern strings used to match against arbitrary claims in the OIDC identity token. Patterns can include * characters to match against any character.
	// A map of claim names to pattern strings used to match against arbitrary claims in the OIDC identity token. Patterns can include `*` characters to match against any character.
	// +mapType=granular
	CustomClaimRules map[string]*string `json:"customClaimRules,omitempty" tf:"custom_claim_rules,omitempty"`

	// (String) A description of the federated identity consisting of alphanumeric characters. Defaults to "".
	// A description of the federated identity consisting of alphanumeric characters. Defaults to `""`.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The client ID, also known as the key id. Used with an OIDC identity token to generate access tokens.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The issuer of the OIDC identity token used in the token exchange. Must be a valid and publicly reachable https:// URL.
	// The issuer of the OIDC identity token used in the token exchange. Must be a valid and publicly reachable https:// URL.
	Issuer *string `json:"issuer,omitempty" tf:"issuer,omitempty"`

	// (Set of String) Scopes to grant to the federated identity. See https://tailscale.com/kb/1623/ for a list of available scopes.
	// Scopes to grant to the federated identity. See https://tailscale.com/kb/1623/ for a list of available scopes.
	// +listType=set
	Scopes []*string `json:"scopes,omitempty" tf:"scopes,omitempty"`

	// (String) The pattern used when matching against the sub claim from an OIDC identity token. Patterns can include * characters to match against any character.
	// The pattern used when matching against the `sub` claim from an OIDC identity token. Patterns can include `*` characters to match against any character.
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`

	// (Set of String) A list of tags that access tokens generated for the federated identity will be able to assign to devices. Mandatory if the scopes include "devices:core" or "auth_keys".
	// A list of tags that access tokens generated for the federated identity will be able to assign to devices. Mandatory if the scopes include "devices:core" or "auth_keys".
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) The updated timestamp of the key in RFC3339 format
	// The updated timestamp of the key in RFC3339 format
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// (String) ID of the user who created this federated identity, empty for federated identities created by other trust credentials.
	// ID of the user who created this federated identity, empty for federated identities created by other trust credentials.
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type IdentityParameters struct {

	// (String) The value used when matching against the aud claim from an OIDC identity token. Specifying the audience is optional as Tailscale will generate a secure audience at creation time by default.   It is recommended to let Tailscale generate the audience unless the identity provider you are integrating with requires a specific audience format.
	// The value used when matching against the `aud` claim from an OIDC identity token. Specifying the audience is optional as Tailscale will generate a secure audience at creation time by default.   It is recommended to let Tailscale generate the audience unless the identity provider you are integrating with requires a specific audience format.
	// +kubebuilder:validation:Optional
	Audience *string `json:"audience,omitempty" tf:"audience,omitempty"`

	// (Map of String) A map of claim names to pattern strings used to match against arbitrary claims in the OIDC identity token. Patterns can include * characters to match against any character.
	// A map of claim names to pattern strings used to match against arbitrary claims in the OIDC identity token. Patterns can include `*` characters to match against any character.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	CustomClaimRules map[string]*string `json:"customClaimRules,omitempty" tf:"custom_claim_rules,omitempty"`

	// (String) A description of the federated identity consisting of alphanumeric characters. Defaults to "".
	// A description of the federated identity consisting of alphanumeric characters. Defaults to `""`.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The issuer of the OIDC identity token used in the token exchange. Must be a valid and publicly reachable https:// URL.
	// The issuer of the OIDC identity token used in the token exchange. Must be a valid and publicly reachable https:// URL.
	// +kubebuilder:validation:Optional
	Issuer *string `json:"issuer,omitempty" tf:"issuer,omitempty"`

	// (Set of String) Scopes to grant to the federated identity. See https://tailscale.com/kb/1623/ for a list of available scopes.
	// Scopes to grant to the federated identity. See https://tailscale.com/kb/1623/ for a list of available scopes.
	// +kubebuilder:validation:Optional
	// +listType=set
	Scopes []*string `json:"scopes,omitempty" tf:"scopes,omitempty"`

	// (String) The pattern used when matching against the sub claim from an OIDC identity token. Patterns can include * characters to match against any character.
	// The pattern used when matching against the `sub` claim from an OIDC identity token. Patterns can include `*` characters to match against any character.
	// +kubebuilder:validation:Optional
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`

	// (Set of String) A list of tags that access tokens generated for the federated identity will be able to assign to devices. Mandatory if the scopes include "devices:core" or "auth_keys".
	// A list of tags that access tokens generated for the federated identity will be able to assign to devices. Mandatory if the scopes include "devices:core" or "auth_keys".
	// +kubebuilder:validation:Optional
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

// IdentitySpec defines the desired state of Identity
type IdentitySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     IdentityParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IdentityInitParameters `json:"initProvider,omitempty"`
}

// IdentityStatus defines the observed state of Identity.
type IdentityStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        IdentityObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Identity is the Schema for the Identitys API. The federated_identity resource allows you to create federated identities to programmatically interact with the Tailscale API using workload identity federation.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,tailscale}
type Identity struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.issuer) || (has(self.initProvider) && has(self.initProvider.issuer))",message="spec.forProvider.issuer is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.scopes) || (has(self.initProvider) && has(self.initProvider.scopes))",message="spec.forProvider.scopes is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.subject) || (has(self.initProvider) && has(self.initProvider.subject))",message="spec.forProvider.subject is a required parameter"
	Spec   IdentitySpec   `json:"spec"`
	Status IdentityStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IdentityList contains a list of Identitys
type IdentityList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Identity `json:"items"`
}

// Repository type metadata.
var (
	Identity_Kind             = "Identity"
	Identity_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Identity_Kind}.String()
	Identity_KindAPIVersion   = Identity_Kind + "." + CRDGroupVersion.String()
	Identity_GroupVersionKind = CRDGroupVersion.WithKind(Identity_Kind)
)

func init() {
	SchemeBuilder.Register(&Identity{}, &IdentityList{})
}
