// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type IntegrationInitParameters struct {

	// (String) Unique identifier for your client.
	// Unique identifier for your client.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String, Sensitive) The secret (auth key, token, etc.) used to authenticate with the provider.
	// The secret (auth key, token, etc.) used to authenticate with the provider.
	ClientSecretSecretRef v1.SecretKeySelector `json:"clientSecretSecretRef" tf:"-"`

	// (String) Identifies which of the provider's clouds to integrate with.
	// Identifies which of the provider's clouds to integrate with.
	CloudID *string `json:"cloudId,omitempty" tf:"cloud_id,omitempty"`

	// party provider for posture data. Valid values are falcon, fleet, huntress, intune, jamfpro, kandji, kolide, and sentinelone.
	// The third-party provider for posture data. Valid values are `falcon`, `fleet`, `huntress`, `intune`, `jamfpro`, `kandji`, `kolide`, and `sentinelone`.
	PostureProvider *string `json:"postureProvider,omitempty" tf:"posture_provider,omitempty"`

	// (String) The Microsoft Intune directory (tenant) ID. For other providers, this is left blank.
	// The Microsoft Intune directory (tenant) ID. For other providers, this is left blank.
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`
}

type IntegrationObservation struct {

	// (String) Unique identifier for your client.
	// Unique identifier for your client.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String) Identifies which of the provider's clouds to integrate with.
	// Identifies which of the provider's clouds to integrate with.
	CloudID *string `json:"cloudId,omitempty" tf:"cloud_id,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// party provider for posture data. Valid values are falcon, fleet, huntress, intune, jamfpro, kandji, kolide, and sentinelone.
	// The third-party provider for posture data. Valid values are `falcon`, `fleet`, `huntress`, `intune`, `jamfpro`, `kandji`, `kolide`, and `sentinelone`.
	PostureProvider *string `json:"postureProvider,omitempty" tf:"posture_provider,omitempty"`

	// (String) The Microsoft Intune directory (tenant) ID. For other providers, this is left blank.
	// The Microsoft Intune directory (tenant) ID. For other providers, this is left blank.
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`
}

type IntegrationParameters struct {

	// (String) Unique identifier for your client.
	// Unique identifier for your client.
	// +kubebuilder:validation:Optional
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String, Sensitive) The secret (auth key, token, etc.) used to authenticate with the provider.
	// The secret (auth key, token, etc.) used to authenticate with the provider.
	// +kubebuilder:validation:Optional
	ClientSecretSecretRef v1.SecretKeySelector `json:"clientSecretSecretRef" tf:"-"`

	// (String) Identifies which of the provider's clouds to integrate with.
	// Identifies which of the provider's clouds to integrate with.
	// +kubebuilder:validation:Optional
	CloudID *string `json:"cloudId,omitempty" tf:"cloud_id,omitempty"`

	// party provider for posture data. Valid values are falcon, fleet, huntress, intune, jamfpro, kandji, kolide, and sentinelone.
	// The third-party provider for posture data. Valid values are `falcon`, `fleet`, `huntress`, `intune`, `jamfpro`, `kandji`, `kolide`, and `sentinelone`.
	// +kubebuilder:validation:Optional
	PostureProvider *string `json:"postureProvider,omitempty" tf:"posture_provider,omitempty"`

	// (String) The Microsoft Intune directory (tenant) ID. For other providers, this is left blank.
	// The Microsoft Intune directory (tenant) ID. For other providers, this is left blank.
	// +kubebuilder:validation:Optional
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`
}

// IntegrationSpec defines the desired state of Integration
type IntegrationSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     IntegrationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IntegrationInitParameters `json:"initProvider,omitempty"`
}

// IntegrationStatus defines the observed state of Integration.
type IntegrationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        IntegrationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Integration is the Schema for the Integrations API. The posture_integration resource allows you to manage integrations with device posture data providers. See https://tailscale.com/kb/1288/device-posture for more information.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,tailscale}
type Integration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clientSecretSecretRef)",message="spec.forProvider.clientSecretSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.postureProvider) || (has(self.initProvider) && has(self.initProvider.postureProvider))",message="spec.forProvider.postureProvider is a required parameter"
	Spec   IntegrationSpec   `json:"spec"`
	Status IntegrationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IntegrationList contains a list of Integrations
type IntegrationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Integration `json:"items"`
}

// Repository type metadata.
var (
	Integration_Kind             = "Integration"
	Integration_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Integration_Kind}.String()
	Integration_KindAPIVersion   = Integration_Kind + "." + CRDGroupVersion.String()
	Integration_GroupVersionKind = CRDGroupVersion.WithKind(Integration_Kind)
)

func init() {
	SchemeBuilder.Register(&Integration{}, &IntegrationList{})
}
