apiVersion: oauth.tailscale.buttah-cloud.io/v1alpha1
kind: Client
metadata:
  annotations:
    meta.upbound.io/example-id: oauth/v1alpha1/client
  labels:
    testing.upbound.io/example-name: sample_client
  name: sample-client
spec:
  forProvider:
    description: sample client
    scopes:
    - all:read
    tags:
    - tag:test
